'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MBoardMouseClicker.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property greenLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greenLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property Hello() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hello", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property MBoard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MBoard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property MBoard__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MBoard (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property MBoard1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MBoard1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property redLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 感謝使用 MBoard 開源滑鼠連點器！
        '''
        '''首先，我，510208 衷心感謝所有使用者的支持和使用。MBoard 是一個開源項目，依據 GNUv3 開源條款，我們相信自由軟體的力量，並致力於提供一個方便、實用且開放的滑鼠連點解決方案。
        '''
        '''在這個項目中，我們的目標是為使用者提供一個強大而靈活的滑鼠連點工具，並持續改進和優化它，讓每個使用者都能體驗到無比愉悅的連點體驗。
        '''
        '''感謝所有熱心參與此項目的開發者，你們的貢獻是 MBoard 成功的重要原因。沒有你們的努力和才智，我們無法實現這個優秀的滑鼠連點器。
        '''
        '''同時，我們也要感謝所有提供回饋和意見的使用者。你們的寶貴建議讓我們更了解 MBoard 的不足之處，並推動我們不斷改進和完善它，以滿足更多人的需求。
        '''
        '''作為開源項目，我們相信知識的分享和合作的精神。因此，我們歡迎任何人參與到 MBoard 的開發中來，一同努力，讓這個項目變得更加強大和便捷。
        '''
        '''最後，再次感謝所有支持和使用 MBoard 的朋友們。我們期待著與您一同見證 MBoard 不斷進步和發展的過程，並為您提供更好的使用體驗。
        '''
        '''感謝！
        '''
        '''作者 510208 敬上 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property thanks() As String
            Get
                Return ResourceManager.GetString("thanks", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
